"use client";

import { useCallback, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { Edit3, Plus, Trash2, X } from "lucide-react";
import Frame from "@/components/Frame/Frame";
import { apiRequest } from "@/components/api";

const EMPTY = { title: "", slug: "", category: "", image: "", imageAlt: "", description: "", overview: "", challenge: "", solution: "", results: "", techStack: "", projectUrl: "", order: 0, isActive: true, isFeatured: true };
const input = "mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-normal";

function ProjectForm({ project, onClose, onSave }) {
  const [form, setForm] = useState(project || EMPTY); const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); onSave({ ...form, results: form.results.split("\n").map((item) => item.trim()).filter(Boolean), techStack: form.techStack.split(",").map((item) => item.trim()).filter(Boolean) }); };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4"><form onSubmit={submit} className="mx-auto my-4 w-full max-w-3xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#d26c51]">Portfolio case study</p><h2 className="text-xl font-bold">{project?._id ? "Edit project" : "Add project"}</h2></div><button type="button" onClick={onClose}><X /></button></div><div className="grid gap-4 md:grid-cols-2">{[["title", "Project title", true], ["slug", "URL slug (optional)"], ["category", "Category"], ["order", "Display order"], ["image", "Image URL / path"], ["imageAlt", "Image alt text"], ["projectUrl", "Live project URL"]].map(([key, label, required]) => <label key={key} className="text-sm font-semibold">{label}<input className={input} type={key === "order" ? "number" : "text"} value={form[key]} onChange={(e) => set(key, e.target.value)} required={required} /></label>)}<label className="md:col-span-2 text-sm font-semibold">Short description<textarea className={`${input} min-h-20`} value={form.description} onChange={(e) => set("description", e.target.value)} required /></label><label className="md:col-span-2 text-sm font-semibold">Project overview<textarea className={`${input} min-h-28`} value={form.overview} onChange={(e) => set("overview", e.target.value)} /></label><label className="text-sm font-semibold">Challenge<textarea className={`${input} min-h-24`} value={form.challenge} onChange={(e) => set("challenge", e.target.value)} /></label><label className="text-sm font-semibold">Solution<textarea className={`${input} min-h-24`} value={form.solution} onChange={(e) => set("solution", e.target.value)} /></label><label className="text-sm font-semibold">Technology <span className="font-normal text-slate-400">(comma separated)</span><input className={input} value={form.techStack} onChange={(e) => set("techStack", e.target.value)} /></label><label className="text-sm font-semibold">Results <span className="font-normal text-slate-400">(one per line)</span><textarea className={`${input} min-h-20`} value={form.results} onChange={(e) => set("results", e.target.value)} /></label></div><div className="mt-4 flex gap-4 text-sm font-semibold"><label><input type="checkbox" checked={form.isActive} onChange={(e) => set("isActive", e.target.checked)} /> Show on frontend</label><label><input type="checkbox" checked={form.isFeatured} onChange={(e) => set("isFeatured", e.target.checked)} /> Feature on home</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button className="rounded-lg bg-[#235056] px-4 py-2 text-sm font-semibold text-white">Save portfolio</button></div></form></div>;
}

export default function PortfolioPage() {
  const [projects, setProjects] = useState([]); const [editing, setEditing] = useState(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); const response = await apiRequest("/admin/projects"); setProjects(response.data || []); } catch (err) { setError(err.message); await Swal.fire({ icon: "error", title: "Portfolio unavailable", text: err.message || "Unable to load projects" }); } }, []); useEffect(() => { load(); }, [load]);
  const save = async (data) => { if (!data.title || !data.description) return Swal.fire({ icon: "warning", title: "Missing details", text: "Project title and short description are required." }); try { const isUpdate = Boolean(editing?._id); await apiRequest(isUpdate ? `/admin/projects/${editing._id}` : "/admin/projects", { method: isUpdate ? "PATCH" : "POST", body: JSON.stringify(data) }); setEditing(null); await load(); await Swal.fire({ icon: "success", title: "Portfolio saved", text: `The project was ${isUpdate ? "updated" : "added"} successfully.`, timer: 1800, showConfirmButton: false }); } catch (err) { await Swal.fire({ icon: "error", title: "Portfolio not saved", text: err.message || "Unable to save project" }); } };
  const remove = async (project) => { const confirmed = await Swal.fire({ icon: "warning", title: "Delete project?", text: `${project.title} will be permanently removed.`, showCancelButton: true, confirmButtonText: "Delete", confirmButtonColor: "#dc2626" }); if (!confirmed.isConfirmed) return; try { await apiRequest(`/admin/projects/${project._id}`, { method: "DELETE" }); await load(); await Swal.fire({ icon: "success", title: "Project deleted", timer: 1600, showConfirmButton: false }); } catch (err) { await Swal.fire({ icon: "error", title: "Delete failed", text: err.message || "Unable to delete project" }); } };
  return <Frame><div className="min-h-full bg-[#f4f6f8] p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-5 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-widest text-[#d26c51]">Dynamic website content</p><h1 className="text-2xl font-bold">Portfolio & case studies</h1><p className="mt-1 text-sm text-slate-500">Add project details, results, technology, image and public links.</p></div><button onClick={() => setEditing(EMPTY)} className="inline-flex items-center gap-2 rounded-lg bg-[#235056] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> Add portfolio</button></div>{error && <p className="mb-4 rounded-lg bg-rose-50 p-3 text-rose-700">{error}</p>}<div className="overflow-hidden rounded-xl border bg-white">{projects.length ? <table className="min-w-full"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Project</th><th className="p-4">Category</th><th className="p-4">Visibility</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{projects.map((project) => <tr key={project._id} className="border-t"><td className="p-4"><b>{project.title}</b><small className="block text-slate-500">/case-studies/{project.slug}</small></td><td className="p-4 text-sm">{project.category}</td><td className="p-4 text-sm">{project.isActive ? (project.isFeatured ? "Visible · Featured" : "Visible") : "Hidden"}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => setEditing({ ...project, techStack: (project.techStack || []).join(", "), results: (project.results || []).join("\n") })} className="rounded-lg border p-2"><Edit3 size={16} /></button><button onClick={() => remove(project)} className="rounded-lg border border-rose-100 bg-rose-50 p-2 text-rose-600"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table> : <p className="p-12 text-center text-sm text-slate-500">No data found.</p>}</div>{editing && <ProjectForm project={editing} onClose={() => setEditing(null)} onSave={save} />}</div></Frame>;
}
