"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, BarChart3, Bell, CheckCircle2, Database, ExternalLink, LayoutPanelTop, MonitorCog, RefreshCw, Settings, ShieldCheck, UserCog } from "lucide-react";
import Frame from "@/components/Frame/Frame";
import { API_BASE_URL, apiRequest, formatDate } from "@/components/api";
import { ContentLoader } from "@/components/AsyncState";

const DEFAULT_PREFS = { compactTables: false, emailAlerts: true, securityAlerts: true, dashboardAutoRefresh: true };
const QUICK_LINKS = [{ label: "Dashboard", href: "/dashboard", icon: BarChart3 }, { label: "Comments", href: "/comments", icon: Bell }, { label: "Content Decay", href: "/content-decay", icon: Activity }, { label: "Media Library", href: "/media", icon: Database }];

function StatusPill({ status }) { const online = status === "online"; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-bold capitalize ${online ? "border-emerald-200 bg-emerald-50 text-emerald-700" : status === "checking" ? "border-[#0f5960]/20 bg-[#e7f1f0] text-[#0f5960]" : "border-rose-200 bg-rose-50 text-rose-700"}`}><i className={`h-2 w-2 rounded-full ${online ? "bg-emerald-500" : status === "checking" ? "animate-pulse bg-[#0f5960]" : "bg-rose-500"}`}/>{status}</span>; }
function StatCard({ label, value, caption, icon: Icon, color = "teal" }) { const tones = { teal: "bg-[#0f5960]/10 text-[#0f5960]", orange: "bg-[#d85e3d]/10 text-[#d85e3d]", gold: "bg-[#f7c56d]/25 text-[#8a5b09]", blue: "bg-[#5c9baa]/15 text-[#276370]" }; return <article className="rounded-2xl border border-[#0f5960]/12 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-[#5d7679]">{label}</p><p className="mt-2 truncate text-xl font-black text-[#123f46]">{value}</p></div><span className={`rounded-xl p-2.5 ${tones[color]}`}><Icon size={18}/></span></div><p className="mt-3 text-xs text-slate-500">{caption}</p></article>; }
function ToggleRow({ label, description, checked, onChange }) { return <div className="flex items-center justify-between gap-5 rounded-2xl border border-[#0f5960]/10 bg-[#f8fbfa] p-4"><div><p className="text-sm font-bold text-[#123f46]">{label}</p><p className="mt-1 text-xs leading-5 text-[#5d7679]">{description}</p></div><button type="button" onClick={() => onChange(!checked)} aria-pressed={checked} className={`relative h-7 w-12 shrink-0 rounded-full transition ${checked ? "bg-[#0f5960]" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`}/></button></div>; }

export default function SettingsPage() {
  const [profile, setProfile] = useState(null); const [analytics, setAnalytics] = useState(null); const [prefs, setPrefs] = useState(DEFAULT_PREFS); const [apiStatus, setApiStatus] = useState("checking"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); setApiStatus("checking"); try { const saved = window.localStorage.getItem("kraviona_admin_settings"); if (saved) setPrefs({ ...DEFAULT_PREFS, ...JSON.parse(saved) }); const [me, dashboard] = await Promise.all([apiRequest("/me"), apiRequest("/analytics/dashboard")]); setProfile(me.data || null); setAnalytics(dashboard.data || null); setApiStatus("online"); } catch (err) { setApiStatus("offline"); setError(err.message || "Unable to load settings."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { window.localStorage.setItem("kraviona_admin_settings", JSON.stringify(prefs)); }, [prefs]);
  const profileName = useMemo(() => profile?.name || profile?.username || "Admin", [profile]);
  const update = (key, value) => setPrefs((previous) => ({ ...previous, [key]: value }));

  return <Frame><main className="min-h-full bg-[#edf5f4] px-4 py-6 sm:px-6 lg:px-9 lg:py-8"><div className="mx-auto max-w-6xl">
    <section className="relative mb-6 overflow-hidden rounded-3xl border border-[#0f5960]/20 bg-gradient-to-br from-[#123f46] via-[#0f5960] to-[#1b6870] p-6 text-white shadow-xl shadow-[#0f5960]/15 sm:p-8"><div className="absolute -right-14 -top-14 h-52 w-52 rounded-full bg-[#f7c56d]/15 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f7d994]">Control centre</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-black"><Settings size={27}/> Settings</h1><p className="mt-2 text-sm text-[#dcebea]">Your admin workspace preferences, connection health and shortcuts.</p></div><div className="flex flex-wrap items-center gap-3"><StatusPill status={apiStatus}/><button type="button" onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-[#f7c56d] px-4 py-2.5 text-sm font-bold text-[#123f46] transition hover:bg-[#ffe09c] disabled:opacity-60"><RefreshCw size={16} className={loading ? "animate-spin" : ""}/> Refresh status</button></div></div></section>
    {error && <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-medium text-amber-800">{error}</div>}
    {loading && !profile ? <div className="rounded-2xl bg-white"><ContentLoader label="Loading your settings…"/></div> : <><section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="API status" value={apiStatus === "online" ? "Connected" : apiStatus} caption="Authenticated backend connection" icon={Database}/><StatCard label="Current account" value={profileName} caption={profile?.role ? `Role: ${profile.role.replace("_", " ")}` : "Current admin session"} icon={UserCog} color="blue"/><StatCard label="Posts tracked" value={analytics?.summary?.postsTotal ?? "—"} caption="Content available in CMS" icon={LayoutPanelTop} color="orange"/><StatCard label="Last sync" value={analytics?.generatedAt ? new Date(analytics.generatedAt).toLocaleTimeString("en-IN", {hour:"2-digit", minute:"2-digit"}) : "—"} caption={analytics?.generatedAt ? formatDate(analytics.generatedAt) : "No analytics sync yet"} icon={Activity} color="gold"/></section>
      <section className="grid grid-cols-1 gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-[#0f5960]/12 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex gap-3"><span className="rounded-xl bg-[#e7f1f0] p-2.5 text-[#0f5960]"><MonitorCog size={19}/></span><div><h2 className="font-black text-[#123f46]">Workspace preferences</h2><p className="mt-1 text-xs text-[#5d7679]">Preferences are saved to this browser.</p></div></div><div className="space-y-3"><ToggleRow label="Compact tables" description="Use denser spacing when viewing CMS lists." checked={prefs.compactTables} onChange={(value) => update("compactTables", value)}/><ToggleRow label="Email alerts" description="Keep lead, message and audience notifications enabled." checked={prefs.emailAlerts} onChange={(value) => update("emailAlerts", value)}/><ToggleRow label="Security alerts" description="Highlight sign-in and moderation-related notices." checked={prefs.securityAlerts} onChange={(value) => update("securityAlerts", value)}/><ToggleRow label="Dashboard auto refresh" description="Allow overview widgets to refresh while the panel is open." checked={prefs.dashboardAutoRefresh} onChange={(value) => update("dashboardAutoRefresh", value)}/></div></article>
      <article className="rounded-3xl border border-[#0f5960]/12 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex gap-3"><span className="rounded-xl bg-[#f7c56d]/25 p-2.5 text-[#8a5b09]"><ShieldCheck size={19}/></span><div><h2 className="font-black text-[#123f46]">Security & quick access</h2><p className="mt-1 text-xs text-[#5d7679]">Protected account and system information.</p></div></div><div className="space-y-3"><div className="rounded-2xl border border-[#0f5960]/10 bg-[#f8fbfa] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold text-[#123f46]">API connection</p><p className="mt-1 text-xs text-[#5d7679]">{API_BASE_URL.replace(/^https?:\/\//, "")}</p></div><StatusPill status={apiStatus}/></div></div><div className="flex items-center gap-3 rounded-2xl border border-[#0f5960]/10 bg-[#f8fbfa] p-4"><CheckCircle2 className="text-emerald-600" size={19}/><div><p className="text-sm font-bold text-[#123f46]">Protected session</p><p className="mt-1 text-xs text-[#5d7679]">Access is validated by admin authentication.</p></div></div><div className="rounded-2xl border border-[#0f5960]/10 bg-[#f8fbfa] p-4"><p className="text-xs font-black uppercase tracking-[0.14em] text-[#5d7679]">Quick links</p><div className="mt-3 grid grid-cols-2 gap-2">{QUICK_LINKS.map(({label,href,icon:Icon}) => <Link key={href} href={href} className="flex items-center justify-between rounded-xl border border-[#0f5960]/15 bg-white px-3 py-2.5 text-xs font-bold text-[#0f5960] transition hover:border-[#d85e3d]/50 hover:bg-[#fff7f3] hover:text-[#d85e3d]"><span className="flex items-center gap-2"><Icon size={14}/>{label}</span><ExternalLink size={13}/></Link>)}</div></div></div></article></section></>}
  </div></main></Frame>;
}
