"use client";

import { useEffect, useState } from "react";
import Frame from "@/components/Frame/Frame";
import { apiRequest, formatDate } from "@/components/api";
import Swal from "sweetalert2";
import { ContentLoader, EmptyState } from "@/components/AsyncState";

export default function LoginHistoryPage() {
  const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { apiRequest("/login-history?limit=100").then((result) => setHistory(result.data || [])).catch((err) => { const message = err.message || "Unable to load login history"; setError(message); Swal.fire({ icon: "error", title: "History unavailable", text: message }); }).finally(() => setLoading(false)); }, []);
  return <Frame><div className="min-h-full bg-[#edf5f4] p-5 sm:p-6 lg:p-8"><div className="rounded-2xl border border-[#0f5960]/20 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d85e3d]">Security audit</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Login history</h1><p className="mt-1 text-sm text-slate-500">Super admins see all activity; everyone else sees only their own sign-ins.</p></div>{error ? <p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</p> : <div className="mt-5 overflow-hidden rounded-2xl border border-[#0f5960]/20 bg-white shadow-sm">{loading ? <ContentLoader label="Loading login history…" /> : history.length ? <div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-[#e7f1f0] text-left text-xs font-bold uppercase tracking-wide text-[#0a454b]"><tr><th className="p-4">Account</th><th className="p-4">Date & time</th><th className="p-4">IP address</th><th className="p-4">Method</th></tr></thead><tbody>{history.map((item) => <tr key={item._id} className="border-t border-slate-200 hover:bg-[#f8fbfa]"><td className="p-4"><div className="flex items-center gap-3">{item.user?.avatar ? <img src={item.user.avatar} alt="" className="h-9 w-9 rounded-full object-cover" /> : <span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e7f1f0] text-xs font-bold text-[#0f5960]">{item.user?.name?.slice(0, 2).toUpperCase() || "--"}</span>}<span><b className="block text-slate-900">{item.user?.name || "No data found."}</b><small className="block text-slate-500">{item.user?.email || ""}</small></span></div></td><td className="p-4 text-sm text-slate-700">{formatDate(item.createdAt)}<span className="ml-2 text-slate-500">{new Date(item.createdAt).toLocaleTimeString()}</span></td><td className="p-4 text-sm text-slate-700">{item.ipAddress || "No data found."}</td><td className="p-4"><span className="rounded-full bg-[#e7f1f0] px-3 py-1 text-xs font-semibold capitalize text-[#0a454b]">{item.method}</span></td></tr>)}</tbody></table></div> : <EmptyState title="No login activity found" message="New successful sign-ins will appear here." />}</div>}</div></Frame>;
}
