"use client";

import { useCallback, useEffect, useState } from "react";
import { Edit3, Loader2, Plus, Trash2, X } from "lucide-react";
import Frame from "@/components/Frame/Frame";
import { apiRequest } from "@/components/api";
import Swal from "sweetalert2";

const EMPTY = { title: "", slug: "", category: "", description: "", features: "", order: 0, isActive: true };

function ServiceForm({ service, saving, onClose, onSave }) {
  const [form, setForm] = useState(service || EMPTY);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); onSave({ ...form, features: form.features.split(",").map((item) => item.trim()).filter(Boolean) }); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={submit} className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#d26c51]">Website catalogue</p><h2 className="text-xl font-bold">{service?._id ? "Edit service" : "Add service"}</h2></div><button type="button" onClick={onClose} className="p-2 text-slate-500"><X /></button></div><div className="grid gap-4 md:grid-cols-2">{[["title", "Service title"], ["slug", "URL slug (optional)"], ["category", "Category"], ["order", "Display order"]].map(([key, label]) => <label key={key} className="text-sm font-semibold text-slate-700">{label}<input type={key === "order" ? "number" : "text"} value={form[key]} onChange={(e) => set(key, e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-normal" required={key === "title"} /></label>)}<label className="md:col-span-2 text-sm font-semibold text-slate-700">Description<textarea value={form.description} onChange={(e) => set("description", e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-slate-200 px-3 py-2 font-normal" required /></label><label className="md:col-span-2 text-sm font-semibold text-slate-700">Features <span className="font-normal text-slate-400">(comma separated)</span><input value={form.features} onChange={(e) => set("features", e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label></div><label className="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isActive} onChange={(e) => set("isActive", e.target.checked)} /> Show on website</label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#235056] px-4 py-2 text-sm font-semibold text-white">{saving && <Loader2 size={16} className="animate-spin" />}Save service</button></div></form></div>;
}

export default function ServicesPage() {
  const [services, setServices] = useState([]); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); const result = await apiRequest("/admin/services"); setServices(result.data || []); } catch (err) { setError(err.message || "Unable to load services"); } }, []);
  useEffect(() => { load(); }, [load]);
  const save = async (data) => { if (!data.title || !data.description) { await Swal.fire({ icon: "warning", title: "Missing details", text: "Enter a service title and description before saving." }); return; } try { setSaving(true); const endpoint = editing?._id ? `/admin/services/${editing._id}` : "/admin/services"; await apiRequest(endpoint, { method: editing?._id ? "PATCH" : "POST", body: JSON.stringify(data) }); const action = editing?._id ? "updated" : "created"; setEditing(null); await load(); await Swal.fire({ icon: "success", title: "Service saved", text: `The service was ${action} and is ready for the website.`, timer: 1800, showConfirmButton: false }); } catch (err) { const message = err.message || "Unable to save service"; setError(message); await Swal.fire({ icon: "error", title: "Service not saved", text: message }); } finally { setSaving(false); } };
  const remove = async (service) => { const confirmation = await Swal.fire({ icon: "warning", title: "Delete service?", text: `${service.title} will be permanently removed.`, showCancelButton: true, confirmButtonText: "Delete", confirmButtonColor: "#dc2626" }); if (!confirmation.isConfirmed) return; try { await apiRequest(`/admin/services/${service._id}`, { method: "DELETE" }); await load(); await Swal.fire({ icon: "success", title: "Service deleted", text: "The service has been removed.", timer: 1800, showConfirmButton: false }); } catch (err) { const message = err.message || "Unable to delete service"; setError(message); await Swal.fire({ icon: "error", title: "Delete failed", text: message }); } };
  return <Frame><div className="min-h-full bg-[#f4f6f8] p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-5 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-widest text-[#d26c51]">Dynamic website content</p><h1 className="text-2xl font-bold">Services</h1><p className="mt-1 text-sm text-slate-500">Services marked active appear automatically on the website.</p></div><button onClick={() => setEditing(EMPTY)} className="inline-flex items-center gap-2 rounded-lg bg-[#235056] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> Add service</button></div>{error && <p className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="overflow-hidden rounded-xl border bg-white shadow-sm">{services.length ? <table className="min-w-full"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Service</th><th className="p-4">Category</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{services.map((service) => <tr key={service._id} className="border-t"><td className="p-4"><p className="font-semibold">{service.title}</p><p className="text-sm text-slate-500">/{service.slug}</p></td><td className="p-4 text-sm">{service.category}</td><td className="p-4 text-sm">{service.isActive ? "Visible" : "Hidden"}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => setEditing({ ...service, features: (service.features || []).join(", ") })} className="rounded-lg border p-2"><Edit3 size={16} /></button><button onClick={() => remove(service)} className="rounded-lg border border-rose-100 bg-rose-50 p-2 text-rose-600"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table> : <p className="p-12 text-center text-sm text-slate-500">No data found.</p>}</div>{editing && <ServiceForm service={editing} saving={saving} onClose={() => setEditing(null)} onSave={save} />}</div></Frame>;
}
